# course_data.py
# -*- coding: utf-8 -*-

# ✅ Data Science Students
data_science_students = [
    {"id": "DS6846", "name": "Alex Carter", "attendance": 76, "exam_status": "Fit to Sit", "exam_score": 81,
     "a1_score": 59, "a1_status": "Completed", "a1_penalty": "", "a2_score": 81, "a2_status": "Completed",
     "a2_penalty": "🚩 Academic Misconduct", "status": "Enrolled"},
    {"id": "DS6478", "name": "Bella Sanders", "attendance": 98, "exam_status": "Fit to Sit", "exam_score": 53,
     "a1_score": 78, "a1_status": "Completed", "a1_penalty": "", "a2_score": 50, "a2_status": "Completed",
     "a2_penalty": "", "status": "Enrolled"},
    {"id": "DS1813", "name": "Cameron Hughes", "attendance": 60, "exam_status": "Fit to Sit", "exam_score": 52,
     "a1_score": 85, "a1_status": "Completed", "a1_penalty": "", "a2_score": 78, "a2_status": "Completed",
     "a2_penalty": "", "status": "Enrolled"},
    {"id": "DS9754", "name": "Diana Wright", "attendance": 39, "exam_status": "Fit to Sit", "exam_score": 84,
     "a1_score": 53, "a1_status": "Completed", "a1_penalty": "", "a2_score": 95, "a2_status": "Completed",
     "a2_penalty": "", "status": "Enrolled"},
    {"id": "DS4378", "name": "Ethan Parker", "attendance": 95, "exam_status": "Fit to Sit", "exam_score": 76,
     "a1_score": 73, "a1_status": "Completed", "a1_penalty": "", "a2_score": 87, "a2_status": "Completed",
     "a2_penalty": "", "status": "Enrolled"},
    {"id": "DS9791", "name": "Felicity James", "attendance": 93, "exam_status": "Fit to Sit", "exam_score": 53,
     "a1_score": 94, "a1_status": "Completed", "a1_penalty": "", "a2_score": 76, "a2_status": "Completed",
     "a2_penalty": "", "status": "Enrolled"},
    {"id": "DS2011", "name": "Gabriel Lewis", "attendance": 94, "exam_status": "Fit to Sit", "exam_score": 80,
     "a1_score": 94, "a1_status": "Completed", "a1_penalty": "🚩 Lateness Penalty (-5%)", "a2_score": 77,
     "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "DS6655", "name": "Hannah Stone", "attendance": 82, "exam_status": "Fit to Sit", "exam_score": 54,
     "a1_score": 71, "a1_status": "Completed", "a1_penalty": "", "a2_score": 70, "a2_status": "Completed",
     "a2_penalty": "", "status": "Enrolled"},
    {"id": "DS6446", "name": "Ian Turner", "attendance": 100, "exam_status": "Fit to Sit", "exam_score": 68,
     "a1_score": 95, "a1_status": "Completed", "a1_penalty": "", "a2_score": 78, "a2_status": "Completed",
     "a2_penalty": "", "status": "Enrolled"},
    {"id": "DS8178", "name": "Jasmine Collins", "attendance": 32, "exam_status": "Fit to Sit", "exam_score": 73,
     "a1_score": 78, "a1_status": "Completed", "a1_penalty": "", "a2_score": 75, "a2_status": "Completed",
     "a2_penalty": "🚩 Lateness Penalty (-5%)", "status": "Enrolled"},
    {"id": "DS2556", "name": "Kevin Morris", "attendance": 41, "exam_status": "Fit to Sit", "exam_score": 81,
     "a1_score": 72, "a1_status": "Completed", "a1_penalty": "", "a2_score": 91, "a2_status": "Completed",
     "a2_penalty": "🚩 Academic Misconduct", "status": "Enrolled"},
    {"id": "DS1387", "name": "Lara Watson", "attendance": 91, "exam_status": "Fit to Sit", "exam_score": 74,
     "a1_score": 65, "a1_status": "Completed", "a1_penalty": "", "a2_score": 84, "a2_status": "Completed",
     "a2_penalty": "", "status": "Enrolled"},
    {"id": "DS5339", "name": "Michael Griffin", "attendance": 81, "exam_status": "Fit to Sit", "exam_score": 81,
     "a1_score": 92, "a1_status": "Completed", "a1_penalty": "", "a2_score": 70, "a2_status": "Completed",
     "a2_penalty": "", "status": "Enrolled"},
    {"id": "DS1766", "name": "Natalie Cooper", "attendance": 93, "exam_status": "Fit to Sit", "exam_score": 82,
     "a1_score": 56, "a1_status": "Completed", "a1_penalty": "🚩 Exceptional Circumstances", "a2_score": 68,
     "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "DS1135", "name": "Owen Richardson", "attendance": 89, "exam_status": "Fit to Sit", "exam_score": 56,
     "a1_score": 90, "a1_status": "Completed", "a1_penalty": "", "a2_score": 81, "a2_status": "Completed",
     "a2_penalty": "", "status": "Enrolled"},
        {"id": "DS5293", "name": "Paige Scott", "attendance": 91, "exam_status": "Fit to Sit", "exam_score": 95,
     "a1_score": 66, "a1_status": "Completed", "a1_penalty": "", "a2_score": 55, "a2_status": "Completed",
     "a2_penalty": "", "status": "Enrolled"},
    {"id": "DS4568", "name": "Quentin Ramirez", "attendance": 99, "exam_status": "Fit to Sit", "exam_score": 52,
     "a1_score": 82, "a1_status": "Completed", "a1_penalty": "🚩 Lateness Penalty (-5%)", "a2_score": 0,
     "a2_status": "Not Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "DS3602", "name": "Rebecca Bennett", "attendance": 71, "exam_status": "Fit to Sit", "exam_score": 78,
     "a1_score": 78, "a1_status": "Completed", "a1_penalty": "", "a2_score": 79, "a2_status": "Completed",
     "a2_penalty": "", "status": "Enrolled"},
    {"id": "DS4981", "name": "Stephen Howard", "attendance": 71, "exam_status": "Fit to Sit", "exam_score": 80,
     "a1_score": 93, "a1_status": "Completed", "a1_penalty": "", "a2_score": 63, "a2_status": "Completed",
     "a2_penalty": "", "status": "Enrolled"},
    {"id": "DS2366", "name": "Tracy Bell", "attendance": 91, "exam_status": "Fit to Sit", "exam_score": 63,
     "a1_score": 63, "a1_status": "Completed", "a1_penalty": "", "a2_score": 76, "a2_status": "Completed",
     "a2_penalty": "", "status": "Enrolled"},
    {"id": "DS8924", "name": "Ulysses Barnes", "attendance": 71, "exam_status": "Fit to Sit", "exam_score": 54,
     "a1_score": 91, "a1_status": "Completed", "a1_penalty": "", "a2_score": 59, "a2_status": "Completed",
     "a2_penalty": "", "status": "Deferred"},
    {"id": "DS2684", "name": "Victoria Foster", "attendance": 78, "exam_status": "Fit to Sit", "exam_score": 70,
     "a1_score": 71, "a1_status": "Completed", "a1_penalty": "", "a2_score": 50, "a2_status": "Completed",
     "a2_penalty": "", "status": "Enrolled"},
    {"id": "DS2674", "name": "Walter Henderson", "attendance": 84, "exam_status": "Fit to Sit", "exam_score": 65,
     "a1_score": 53, "a1_status": "Completed", "a1_penalty": "", "a2_score": 68, "a2_status": "Completed",
     "a2_penalty": "", "status": "Enrolled"},
    {"id": "DS1149", "name": "Xander Nelson", "attendance": 56, "exam_status": "Fit to Sit", "exam_score": 56,
     "a1_score": 82, "a1_status": "Completed", "a1_penalty": "🚩 Exceptional Circumstances", "a2_score": 52,
     "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "DS5583", "name": "Yvette Campbell", "attendance": 63, "exam_status": "Fit to Sit", "exam_score": 75,
     "a1_score": 75, "a1_status": "Completed", "a1_penalty": "", "a2_score": 62, "a2_status": "Completed",
     "a2_penalty": "", "status": "Enrolled"},
    {"id": "DS1563", "name": "Zane Mitchell", "attendance": 93, "exam_status": "Fit to Sit", "exam_score": 57,
     "a1_score": 80, "a1_status": "Completed", "a1_penalty": "", "a2_score": 85, "a2_status": "Completed",
     "a2_penalty": "", "status": "Enrolled"},
    {"id": "DS6404", "name": "Amelia Ross", "attendance": 70, "exam_status": "Fit to Sit", "exam_score": 54,
     "a1_score": 68, "a1_status": "Completed", "a1_penalty": "🚩 Lateness Penalty (-5%)", "a2_score": 58,
     "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "DS8664", "name": "Benjamin Ward", "attendance": 55, "exam_status": "Fit to Sit", "exam_score": 50,
     "a1_score": 78, "a1_status": "Completed", "a1_penalty": "", "a2_score": 60, "a2_status": "Completed",
     "a2_penalty": "🚩 Academic Misconduct", "status": "Enrolled"},
    {"id": "DS9607", "name": "Chloe Edwards", "attendance": 88, "exam_status": "Fit to Sit", "exam_score": 62,
     "a1_score": 77, "a1_status": "Completed", "a1_penalty": "", "a2_score": 91, "a2_status": "Completed",
     "a2_penalty": "", "status": "Enrolled"},
    {"id": "DS5013", "name": "David Fisher", "attendance": 66, "exam_status": "Fit to Sit", "exam_score": 88,
     "a1_score": 90, "a1_status": "Completed", "a1_penalty": "", "a2_score": 53, "a2_status": "Completed",
     "a2_penalty": "", "status": "Enrolled"},
        {"id": "DS2760", "name": "Emma Butler", "attendance": 60, "exam_status": "Fit to Sit", "exam_score": 82,
     "a1_score": 72, "a1_status": "Completed", "a1_penalty": "", "a2_score": 72, "a2_status": "Completed",
     "a2_penalty": "", "status": "Enrolled"},
    {"id": "DS5971", "name": "Frederick Murphy", "attendance": 69, "exam_status": "Fit to Sit", "exam_score": 92,
     "a1_score": 75, "a1_status": "Completed", "a1_penalty": "", "a2_score": 50, "a2_status": "Completed",
     "a2_penalty": "", "status": "Deferred"},
    {"id": "DS2594", "name": "Grace Price", "attendance": 79, "exam_status": "Fit to Sit", "exam_score": 62,
     "a1_score": 51, "a1_status": "Completed", "a1_penalty": "🚩 Exceptional Circumstances", "a2_score": 91,
     "a2_status": "Completed", "a2_penalty": "", "status": "Dropped"},
    {"id": "DS1207", "name": "Henry Stewart", "attendance": 55, "exam_status": "Fit to Sit", "exam_score": 65,
     "a1_score": 60, "a1_status": "Completed", "a1_penalty": "", "a2_score": 50, "a2_status": "Completed",
     "a2_penalty": "", "status": "Enrolled"},
    {"id": "DS8709", "name": "Isabella Torres", "attendance": 88, "exam_status": "Fit to Sit", "exam_score": 52,
     "a1_score": 54, "a1_status": "Completed", "a1_penalty": "", "a2_score": 90, "a2_status": "Completed",
     "a2_penalty": "", "status": "Enrolled"},
    {"id": "DS9507", "name": "Jackie Peterson", "attendance": 68, "exam_status": "Fit to Sit", "exam_score": 88,
     "a1_score": 92, "a1_status": "Completed", "a1_penalty": "", "a2_score": 92, "a2_status": "Completed",
     "a2_penalty": "", "status": "Enrolled"},
    {"id": "DS1882", "name": "Kurt Bailey", "attendance": 98, "exam_status": "Fit to Sit", "exam_score": 61,
     "a1_score": 88, "a1_status": "Completed", "a1_penalty": "", "a2_score": 54, "a2_status": "Completed",
     "a2_penalty": "", "status": "Enrolled"},
    {"id": "DS9592", "name": "Lucy Jenkins", "attendance": 45, "exam_status": "Fit to Sit", "exam_score": 91,
     "a1_score": 82, "a1_status": "Completed", "a1_penalty": "🚩 Academic Misconduct", "a2_score": 85,
     "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "DS9880", "name": "Mason Cooper", "attendance": 84, "exam_status": "Fit to Sit", "exam_score": 83,
     "a1_score": 0, "a1_status": "Not Completed", "a1_penalty": "", "a2_score": 57,
     "a2_status": "Completed", "a2_penalty": "🚩 Lateness Penalty (-5%)", "status": "Enrolled"},
    {"id": "DS6445", "name": "Nina Adams", "attendance": 91, "exam_status": "Fit to Sit", "exam_score": 73,
     "a1_score": 73, "a1_status": "Completed", "a1_penalty": "", "a2_score": 77, "a2_status": "Completed",
     "a2_penalty": "", "status": "Enrolled"},
    {"id": "DS8511", "name": "Oscar Flores", "attendance": 97, "exam_status": "Absent", "exam_score": 0,
     "a1_score": 56, "a1_status": "Completed", "a1_penalty": "", "a2_score": 91, "a2_status": "Completed",
     "a2_penalty": "", "status": "Deferred"},
    {"id": "DS6948", "name": "Penelope Russell", "attendance": 66, "exam_status": "Fit to Sit", "exam_score": 73,
     "a1_score": 70, "a1_status": "Completed", "a1_penalty": "🚩 Lateness Penalty (-5%)", "a2_score": 95,
     "a2_status": "Completed", "a2_penalty": "🚩 Academic Misconduct", "status": "Enrolled"},
    {"id": "DS5478", "name": "Ryan Powell", "attendance": 93, "exam_status": "Fit to Sit", "exam_score": 90,
     "a1_score": 58, "a1_status": "Completed", "a1_penalty": "🚩 Exceptional Circumstances", "a2_score": 95,
     "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "DS1215", "name": "Sophia Simmons", "attendance": 86, "exam_status": "Fit to Sit", "exam_score": 93,
     "a1_score": 67, "a1_status": "Completed", "a1_penalty": "", "a2_score": 83, "a2_status": "Completed",
     "a2_penalty": "", "status": "Enrolled"},
    {"id": "DS4834", "name": "Theodore White", "attendance": 58, "exam_status": "Fit to Sit", "exam_score": 68,
     "a1_score": 90, "a1_status": "Completed", "a1_penalty": "", "a2_score": 82, "a2_status": "Completed",
     "a2_penalty": "", "status": "Enrolled"},
    {"id": "DS7831", "name": "Ursula Martin", "attendance": 93, "exam_status": "Fit to Sit", "exam_score": 56,
     "a1_score": 0, "a1_status": "Not Completed", "a1_penalty": "🚩 Exceptional Circumstances", "a2_score": 76,
     "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "DS1767", "name": "Vince Brown", "attendance": 98, "exam_status": "Fit to Sit", "exam_score": 78,
     "a1_score": 74, "a1_status": "Completed", "a1_penalty": "", "a2_score": 64, "a2_status": "Completed",
     "a2_penalty": "", "status": "Dropped"},
    {"id": "DS8872", "name": "William Gonzales", "attendance": 76, "exam_status": "Fit to Sit", "exam_score": 62,
     "a1_score": 66, "a1_status": "Completed", "a1_penalty": "", "a2_score": 54, "a2_status": "Completed",
     "a2_penalty": "", "status": "Enrolled"},
    {"id": "DS1907", "name": "Xenia Moore", "attendance": 55, "exam_status": "Fit to Sit", "exam_score": 92,
     "a1_score": 85, "a1_status": "Completed", "a1_penalty": "", "a2_score": 68, "a2_status": "Completed",
     "a2_penalty": "", "status": "Enrolled"},
    {"id": "DS7683", "name": "Zoe Walker", "attendance": 63, "exam_status": "Fit to Sit", "exam_score": 87,
     "a1_score": 61, "a1_status": "Completed", "a1_penalty": "", "a2_score": 0, "a2_status": "Not Completed",
     "a2_penalty": "🚩 Academic Misconduct", "status": "Enrolled"}
]


software_engineering_students = [
    {"id": "SE8946", "name": "Alice Johnson", "attendance": 82, "exam_status": "Fit to Sit", "exam_score": 58, "a1_score": 73, "a1_status": "Completed", "a1_penalty": "", "a2_score": 65, "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "SE5918", "name": "Bob Smith", "attendance": 82, "exam_status": "Fit to Sit", "exam_score": 74, "a1_score": 81, "a1_status": "Completed", "a1_penalty": "", "a2_score": 74, "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "SE7494", "name": "Charlie Davis", "attendance": 95, "exam_status": "Fit to Sit", "exam_score": 75, "a1_score": 0, "a1_status": "Not Completed", "a1_penalty": "🚩 Academic Misconduct", "a2_score": 81, "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "SE1509", "name": "David Martinez", "attendance": 81, "exam_status": "Fit to Sit", "exam_score": 94, "a1_score": 73, "a1_status": "Completed", "a1_penalty": "", "a2_score": 67, "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "SE8253", "name": "Eve Brown", "attendance": 83, "exam_status": "Fit to Sit", "exam_score": 70, "a1_score": 69, "a1_status": "Completed", "a1_penalty": "", "a2_score": 95, "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "SE1744", "name": "Frank Wilson", "attendance": 73, "exam_status": "Fit to Sit", "exam_score": 62, "a1_score": 95, "a1_status": "Completed", "a1_penalty": "🚩 Exceptional Circumstances", "a2_score": 0, "a2_status": "Not Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "SE5043", "name": "Grace Taylor", "attendance": 55, "exam_status": "Fit to Sit", "exam_score": 91, "a1_score": 80, "a1_status": "Completed", "a1_penalty": "", "a2_score": 66, "a2_status": "Completed", "a2_penalty": "🚩 Academic Misconduct", "status": "Enrolled"},
    {"id": "SE8979", "name": "Hank Anderson", "attendance": 80, "exam_status": "Fit to Sit", "exam_score": 62, "a1_score": 87, "a1_status": "Completed", "a1_penalty": "", "a2_score": 71, "a2_status": "Completed", "a2_penalty": "🚩 Exceptional Circumstances", "status": "Enrolled"},

    {"id": "SE1968", "name": "Ivy Thomas", "attendance": 97, "exam_status": "Absent", "exam_score": 0, "a1_score": 79, "a1_status": "Completed", "a1_penalty": "", "a2_score": 79, "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "SE1852", "name": "Jack White", "attendance": 88, "exam_status": "Fit to Sit", "exam_score": 58, "a1_score": 71, "a1_status": "Completed", "a1_penalty": "", "a2_score": 77, "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "SE8330", "name": "Karen Harris", "attendance": 76, "exam_status": "Fit to Sit", "exam_score": 76, "a1_score": 93, "a1_status": "Completed", "a1_penalty": "", "a2_score": 0, "a2_status": "Absent", "a2_penalty": "", "status": "Enrolled"},
    {"id": "SE8811", "name": "Leo Martin", "attendance": 89, "exam_status": "Fit to Sit", "exam_score": 79, "a1_score": 0, "a1_status": "Not Completed", "a1_penalty": "", "a2_score": 94, "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "SE9771", "name": "Mona Clark", "attendance": 70, "exam_status": "Fit to Sit", "exam_score": 55, "a1_score": 76, "a1_status": "Completed", "a1_penalty": "", "a2_score": 92, "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "SE5353", "name": "Nathan Lewis", "attendance": 56, "exam_status": "Fit to Sit", "exam_score": 74, "a1_score": 91, "a1_status": "Completed", "a1_penalty": "🚩 Exceptional Circumstances", "a2_score": 0, "a2_status": "Absent", "a2_penalty": "", "status": "Enrolled"},
    {"id": "SE1179", "name": "Olivia Hall", "attendance": 85, "exam_status": "Fit to Sit", "exam_score": 78, "a1_score": 93, "a1_status": "Completed", "a1_penalty": "", "a2_score": 66, "a2_status": "Completed", "a2_penalty": "", "status": "Dropped"},
    {"id": "SE5838", "name": "Peter Allen", "attendance": 89, "exam_status": "Fit to Sit", "exam_score": 82, "a1_score": 85, "a1_status": "Completed", "a1_penalty": "", "a2_score": 81, "a2_status": "Completed", "a2_penalty": "", "status": "Deferred"},
    {"id": "SE4247", "name": "Quincy Young", "attendance": 62, "exam_status": "Fit to Sit", "exam_score": 89, "a1_score": 0, "a1_status": "Not Completed", "a1_penalty": "", "a2_score": 76, "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "SE4796", "name": "Rachel King", "attendance": 78, "exam_status": "Fit to Sit", "exam_score": 56, "a1_score": 78, "a1_status": "Completed", "a1_penalty": "", "a2_score": 65, "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "SE3642", "name": "Steve Wright", "attendance": 89, "exam_status": "Fit to Sit", "exam_score": 81, "a1_score": 80, "a1_status": "Completed", "a1_penalty": "🚩 Academic Misconduct", "a2_score": 91, "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "SE3570", "name": "Tina Scott", "attendance": 94, "exam_status": "Fit to Sit", "exam_score": 67, "a1_score": 86, "a1_status": "Completed", "a1_penalty": "🚩 Exceptional Circumstances", "a2_score": 0, "a2_status": "Not Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "SE3688", "name": "Uma Green", "attendance": 99, "exam_status": "Fit to Sit", "exam_score": 74, "a1_score": 92, "a1_status": "Completed", "a1_penalty": "", "a2_score": 76, "a2_status": "Completed", "a2_penalty": "", "status": "Deferred"},
    {"id": "SE9940", "name": "Victor Adams", "attendance": 76, "exam_status": "Fit to Sit", "exam_score": 82, "a1_score": 70, "a1_status": "Completed", "a1_penalty": "", "a2_score": 86, "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "SE5462", "name": "Wendy Baker", "attendance": 76, "exam_status": "Fit to Sit", "exam_score": 72, "a1_score": 79, "a1_status": "Completed", "a1_penalty": "", "a2_score": 66, "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "SE4267", "name": "Xander Y. Nelson", "attendance": 75, "exam_status": "Fit to Sit", "exam_score": 63, "a1_score": 91, "a1_status": "Completed", "a1_penalty": "", "a2_score": 92, "a2_status": "Completed", "a2_penalty": "", "status": "Deferred"},
    {"id": "SE2196", "name": "Yvonne Carter", "attendance": 70, "exam_status": "Fit to Sit", "exam_score": 70, "a1_score": 66, "a1_status": "Completed", "a1_penalty": "", "a2_score": 84, "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "SE3056", "name": "Zachary Mitchell", "attendance": 96, "exam_status": "Fit to Sit", "exam_score": 94, "a1_score": 0, "a1_status": "Absent", "a1_penalty": "", "a2_score": 90, "a2_status": "Completed", "a2_penalty": "🚩 Word Count Penalty (-10%)", "status": "Enrolled"},
    {"id": "SE3902", "name": "Aaron Perez", "attendance": 60, "exam_status": "Fit to Sit", "exam_score": 65, "a1_score": 90, "a1_status": "Completed", "a1_penalty": "", "a2_score": 84, "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "SE5236", "name": "Bella Roberts", "attendance": 70, "exam_status": "Fit to Sit", "exam_score": 58, "a1_score": 91, "a1_status": "Completed", "a1_penalty": "", "a2_score": 75, "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "SE9158", "name": "Cody Gonzalez", "attendance": 95, "exam_status": "Fit to Sit", "exam_score": 76, "a1_score": 81, "a1_status": "Completed", "a1_penalty": "", "a2_score": 92, "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "SE8950", "name": "Diana Campbell", "attendance": 93, "exam_status": "Fit to Sit", "exam_score": 61, "a1_score": 95, "a1_status": "Completed", "a1_penalty": "", "a2_score": 84, "a2_status": "Completed", "a2_penalty": "", "status": "Dropped"},
    {"id": "SE1967", "name": "Ethan Rodriguez", "attendance": 100, "exam_status": "Fit to Sit", "exam_score": 84, "a1_score": 96, "a1_status": "Completed", "a1_penalty": "🚩 Word Count Penalty (-10%)", "a2_score": 68, "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "SE8256", "name": "Fiona Moore", "attendance": 92, "exam_status": "Fit to Sit", "exam_score": 74, "a1_score": 89, "a1_status": "Completed", "a1_penalty": "", "a2_score": 87, "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "SE4532", "name": "George Edwards", "attendance": 88, "exam_status": "Fit to Sit", "exam_score": 66, "a1_score": 84, "a1_status": "Completed", "a1_penalty": "", "a2_score": 76, "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "SE1517", "name": "Holly Flores", "attendance": 86, "exam_status": "Fit to Sit", "exam_score": 78, "a1_score": 97, "a1_status": "Completed", "a1_penalty": "", "a2_score": 67, "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "SE7469", "name": "Ian Cooper", "attendance": 97, "exam_status": "Fit to Sit", "exam_score": 75, "a1_score": 81, "a1_status": "Completed", "a1_penalty": "", "a2_score": 69, "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "SE8148", "name": "Julia Murphy", "attendance": 96, "exam_status": "Fit to Sit", "exam_score": 58, "a1_score": 91, "a1_status": "Completed", "a1_penalty": "", "a2_score": 86, "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "SE1419", "name": "Kevin Reed", "attendance": 72, "exam_status": "Fit to Sit", "exam_score": 88, "a1_score": 84, "a1_status": "Completed", "a1_penalty": "", "a2_score": 80, "a2_status": "Completed", "a2_penalty": "🚩 Exceptional Circumstances", "status": "Enrolled"},
    {"id": "SE6287", "name": "Laura Cox", "attendance": 98, "exam_status": "Fit to Sit", "exam_score": 79, "a1_score": 76, "a1_status": "Completed", "a1_penalty": "", "a2_score": 71, "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "SE3159", "name": "Mike Ward", "attendance": 58, "exam_status": "Fit to Sit", "exam_score": 56, "a1_score": 77, "a1_status": "Completed", "a1_penalty": "", "a2_score": 75, "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "SE3655", "name": "Nina Peterson", "attendance": 85, "exam_status": "Fit to Sit", "exam_score": 88, "a1_score": 85, "a1_status": "Completed", "a1_penalty": "", "a2_score": 73, "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "SE9723", "name": "Oscar Gray", "attendance": 70, "exam_status": "Fit to Sit", "exam_score": 79, "a1_score": 86, "a1_status": "Completed", "a1_penalty": "🚩 Word Count Penalty (-10%)", "a2_score": 69, "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "SE9035", "name": "Paula Jenkins", "attendance": 86, "exam_status": "Fit to Sit", "exam_score": 88, "a1_score": 72, "a1_status": "Completed", "a1_penalty": "", "a2_score": 84, "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "SE9083", "name": "Quinn Russell", "attendance": 61, "exam_status": "Fit to Sit", "exam_score": 79, "a1_score": 94, "a1_status": "Completed", "a1_penalty": "", "a2_score": 72, "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "SE2110", "name": "Randy Torres", "attendance": 90, "exam_status": "Fit to Sit", "exam_score": 77, "a1_score": 78, "a1_status": "Completed", "a1_penalty": "", "a2_score": 98, "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "SE6193", "name": "Samantha Stevens", "attendance": 89, "exam_status": "Fit to Sit", "exam_score": 92, "a1_score": 65, "a1_status": "Completed", "a1_penalty": "", "a2_score": 73, "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "SE4227", "name": "Tommy Parker", "attendance": 83, "exam_status": "Fit to Sit", "exam_score": 63, "a1_score": 84, "a1_status": "Completed", "a1_penalty": "", "a2_score": 0, "a2_status": "Not Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "SE1890", "name": "Ursula Evans", "attendance": 71, "exam_status": "Fit to Sit", "exam_score": 84, "a1_score": 92, "a1_status": "Completed", "a1_penalty": "", "a2_score": 71, "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "SE1314", "name": "Vince Morgan", "attendance": 80, "exam_status": "Fit to Sit", "exam_score": 74, "a1_score": 84, "a1_status": "Completed", "a1_penalty": "", "a2_score": 97, "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "SE5890", "name": "Whitney Bell", "attendance": 85, "exam_status": "Fit to Sit", "exam_score": 89, "a1_score": 0, "a1_status": "Absent", "a1_penalty": "", "a2_score": 84, "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "SE3935", "name": "Xavier Phillips", "attendance": 70, "exam_status": "Fit to Sit", "exam_score": 62, "a1_score": 98, "a1_status": "Completed", "a1_penalty": "", "a2_score": 83, "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"}
]



# ✅ Big Data Students
big_data_students = [
    {"id": "DS978628", "name": "Edward Davis", "attendance": 67, "a1_score": 56, "a1_status": "Completed", "a1_penalty": "🚩 Lateness Penalty (-5%)", "status": "Enrolled"},
    {"id": "DS207643", "name": "Emily Rangel", "attendance": 96, "a1_score": 71, "a1_status": "Completed", "a1_penalty": "", "status": "Enrolled"},
    {"id": "DS448471", "name": "Jonathan Pratt", "attendance": 81, "a1_score": 59, "a1_status": "Completed", "a1_penalty": "", "status": "Enrolled"},
    {"id": "DS171220", "name": "James King", "attendance": 72, "a1_score": 84, "a1_status": "Completed", "a1_penalty": "", "status": "Enrolled"},
    {"id": "DS354063", "name": "Jenny Rodgers", "attendance": 92, "a1_score": 54, "a1_status": "Completed", "a1_penalty": "", "status": "Enrolled"},
    {"id": "DS567423", "name": "David Munoz", "attendance": 61, "a1_score": 73, "a1_status": "Completed", "a1_penalty": "", "status": "Enrolled"},
    {"id": "DS919140", "name": "Jonathan Freeman", "attendance": 90, "a1_score": 62, "a1_status": "Completed", "a1_penalty": "", "status": "Enrolled"},
    {"id": "DS554222", "name": "Tammy Rodriguez", "attendance": 95, "a1_score": 93, "a1_status": "Completed", "a1_penalty": "🚩 Word Count Penalty (-10%)", "status": "Enrolled"},
    {"id": "DS717887", "name": "Katie Shah", "attendance": 86, "a1_score": 70, "a1_status": "Completed", "a1_penalty": "", "status": "Enrolled"},
    {"id": "DS326387", "name": "Andrew Robles", "attendance": 87, "a1_score": 79, "a1_status": "Completed", "a1_penalty": "", "status": "Enrolled"},
    {"id": "DS221774", "name": "Paul Gilbert", "attendance": 100, "a1_score": 84, "a1_status": "Completed", "a1_penalty": "", "status": "Enrolled"},
    {"id": "DS880471", "name": "Amy Ray", "attendance": 78, "a1_score": 87, "a1_status": "Completed", "a1_penalty": "🚩 Lateness Penalty (-5%)", "status": "Enrolled"},
    {"id": "DS413838", "name": "Tamara Scott", "attendance": 53, "a1_score": 86, "a1_status": "Completed", "a1_penalty": "", "status": "Enrolled"},
    {"id": "DS517577", "name": "Jennifer Smith", "attendance": 63, "a1_score": 68, "a1_status": "Completed", "a1_penalty": "", "status": "Enrolled"},
    {"id": "DS564722", "name": "Janet Campbell", "attendance": 91, "a1_score": 92, "a1_status": "Completed", "a1_penalty": "", "status": "Enrolled"},
    {"id": "DS685613", "name": "Julie Johnson", "attendance": 66, "a1_score": 82, "a1_status": "Completed", "a1_penalty": "🚩 Word Count Penalty (-10%)", "status": "Enrolled"},
    {"id": "DS375005", "name": "Joseph Miles", "attendance": 93, "a1_score": 89, "a1_status": "Completed", "a1_penalty": "", "status": "Enrolled"},
    {"id": "DS472742", "name": "Aaron Bruce", "attendance": 77, "a1_score": 60, "a1_status": "Completed", "a1_penalty": "", "status": "Enrolled"},
    {"id": "DS589415", "name": "Deborah Lewis", "attendance": 65, "a1_score": 83, "a1_status": "Completed", "a1_penalty": "", "status": "Enrolled"},
    {"id": "DS222664", "name": "Sylvia Lopez", "attendance": 98, "a1_score": 94, "a1_status": "Completed", "a1_penalty": "", "status": "Enrolled"},
    {"id": "DS888435", "name": "Crystal Cunningham", "attendance": 87, "a1_score": 67, "a1_status": "Completed", "a1_penalty": "🚩 Lateness Penalty (-5%)", "status": "Enrolled"},
    {"id": "DS148916", "name": "Katie Powers", "attendance": 95, "a1_score": 56, "a1_status": "Completed", "a1_penalty": "", "status": "Enrolled"},
    {"id": "DS189161", "name": "Jennifer Golden", "attendance": 74, "a1_score": 76, "a1_status": "Completed", "a1_penalty": "", "status": "Enrolled"},
    {"id": "DS282269", "name": "Blake Stuart", "attendance": 83, "a1_score": 88, "a1_status": "Completed", "a1_penalty": "", "status": "Enrolled"},
    {"id": "DS625325", "name": "Patricia Christensen", "attendance": 59, "a1_score": 91, "a1_status": "Completed", "a1_penalty": "", "status": "Enrolled"},
    {"id": "DS970055", "name": "Jennifer Cruz", "attendance": 99, "a1_score": 72, "a1_status": "Completed", "a1_penalty": "", "status": "Enrolled"},
    {"id": "DS736028", "name": "Ashley Ibarra", "attendance": 90, "a1_score": 95, "a1_status": "Completed", "a1_penalty": "", "status": "Enrolled"},
    {"id": "DS103889", "name": "Cynthia Wagner", "attendance": 80, "a1_score": 58, "a1_status": "Completed", "a1_penalty": "🚩 Word Count Penalty (-10%)", "status": "Enrolled"},
    {"id": "DS176395", "name": "Stephen Scott", "attendance": 84, "a1_score": 85, "a1_status": "Completed", "a1_penalty": "", "status": "Enrolled"},
    {"id": "DS346324", "name": "Paul Farrell", "attendance": 78, "a1_score": 69, "a1_status": "Completed", "a1_penalty": "", "status": "Enrolled"},
    {"id": "DS924352", "name": "James Joyce", "attendance": 81, "a1_score": 61, "a1_status": "Completed", "a1_penalty": "", "status": "Enrolled"},
    {"id": "DS156951", "name": "Jill Vaughn", "attendance": 88, "a1_score": 87, "a1_status": "Completed", "a1_penalty": "🚩 Lateness Penalty (-5%)", "status": "Enrolled"},
    {"id": "DS738985", "name": "Benjamin Morton", "attendance": 85, "a1_score": 62, "a1_status": "Completed", "a1_penalty": "", "status": "Enrolled"},
    {"id": "DS575543", "name": "Mary Clark", "attendance": 67, "a1_score": 89, "a1_status": "Completed", "a1_penalty": "", "status": "Enrolled"},
    {"id": "DS712784", "name": "Dominic Ochoa", "attendance": 64, "a1_score": 66, "a1_status": "Completed", "a1_penalty": "", "status": "Enrolled"},
    {"id": "DS157881", "name": "Gregory Schroeder", "attendance": 58, "a1_score": 83, "a1_status": "Completed", "a1_penalty": "🚩 Word Count Penalty (-10%)", "status": "Enrolled"},
    {"id": "DS696276", "name": "Veronica Bishop", "attendance": 73, "a1_score": 76, "a1_status": "Completed", "a1_penalty": "", "status": "Enrolled"},
    {"id": "DS429738", "name": "Lori Garcia", "attendance": 93, "a1_score": 80, "a1_status": "Completed", "a1_penalty": "", "status": "Enrolled"},
    {"id": "DS860936", "name": "Debra Greene", "attendance": 91, "a1_score": 90, "a1_status": "Completed", "a1_penalty": "", "status": "Enrolled"},
    {"id": "DS979451", "name": "Katherine Burnett", "attendance": 60, "a1_score": 77, "a1_status": "Completed", "a1_penalty": "", "status": "Enrolled"},
    {"id": "DS637834", "name": "Timothy Johnson", "attendance": 55, "a1_score": 63, "a1_status": "Completed", "a1_penalty": "", "status": "Enrolled"},
    {"id": "DS341647", "name": "Stephanie Thomas", "attendance": 96, "a1_score": 94, "a1_status": "Completed", "a1_penalty": "", "status": "Enrolled"},
    {"id": "DS319107", "name": "Christine Hernandez", "attendance": 83, "a1_score": 65, "a1_status": "Completed", "a1_penalty": "", "status": "Enrolled"},
    {"id": "DS303158", "name": "Corey Coleman", "attendance": 76, "a1_score": 73, "a1_status": "Completed", "a1_penalty": "🚩 Lateness Penalty (-5%)", "status": "Enrolled"},
    {"id": "DS202090", "name": "Daniel Allen", "attendance": 57, "a1_score": 78, "a1_status": "Completed", "a1_penalty": "", "status": "Enrolled"},
    {"id": "DS193387", "name": "Kiara Alvarado", "attendance": 89, "a1_score": 88, "a1_status": "Completed", "a1_penalty": "", "status": "Enrolled"},
    {"id": "DS771116", "name": "James Carroll", "attendance": 69, "a1_score": 66, "a1_status": "Completed", "a1_penalty": "", "status": "Enrolled"},
    {"id": "DS484027", "name": "Jeffery Douglas", "attendance": 70, "a1_score": 90, "a1_status": "Completed", "a1_penalty": "", "status": "Enrolled"},
    {"id": "DS441355", "name": "Breanna Harper", "attendance": 94, "a1_score": 85, "a1_status": "Completed", "a1_penalty": "", "status": "Enrolled"},
    {"id": "DS947660", "name": "Michael Owens", "attendance": 82, "a1_score": 81, "a1_status": "Completed", "a1_penalty": "", "status": "Enrolled"}
]


web_systems_students = [
    {"id": "SE191705", "name": "Frederick Cox", "attendance": 69, "a1_score": 93, "a1_status": "Completed", "a1_penalty": "🚩 Word Count Penalty (-10%)", "status": "Enrolled"},
    {"id": "SE887523", "name": "Walter Rivera", "attendance": 89, "a1_score": 86, "a1_status": "Completed", "a1_penalty": "🚩 Lateness Penalty (-5%)", "status": "Enrolled"},
    {"id": "SE806477", "name": "Marc Huerta", "attendance": 60, "a1_score": 93, "a1_status": "Completed", "a1_penalty": "", "status": "Enrolled"},
    {"id": "SE330599", "name": "James Parker", "attendance": 76, "a1_score": 88, "a1_status": "Completed", "a1_penalty": "", "status": "Enrolled"},
    {"id": "SE172217", "name": "Rebecca Mendez", "attendance": 60, "a1_score": 53, "a1_status": "Completed", "a1_penalty": "", "status": "Enrolled"},
    {"id": "SE982073", "name": "Justin Anderson", "attendance": 99, "a1_score": 83, "a1_status": "Completed", "a1_penalty": "", "status": "Enrolled"},
    {"id": "SE241158", "name": "Matthew Carroll", "attendance": 81, "a1_score": 69, "a1_status": "Completed", "a1_penalty": "", "status": "Enrolled"},
    {"id": "SE791849", "name": "Adam Mcclure", "attendance": 70, "a1_score": 80, "a1_status": "Completed", "a1_penalty": "🚩 Word Count Penalty (-10%)", "status": "Enrolled"},
    {"id": "SE634373", "name": "Joseph Rice", "attendance": 90, "a1_score": 84, "a1_status": "Completed", "a1_penalty": "", "status": "Enrolled"},
    {"id": "SE174298", "name": "Anthony Jones", "attendance": 62, "a1_score": 86, "a1_status": "Completed", "a1_penalty": "", "status": "Enrolled"},
    {"id": "SE379271", "name": "Peter Villarreal", "attendance": 61, "a1_score": 53, "a1_status": "Completed", "a1_penalty": "🚩 Word Count Penalty (-10%)", "status": "Enrolled"},
    {"id": "SE782987", "name": "Matthew Hines", "attendance": 96, "a1_score": 60, "a1_status": "Completed", "a1_penalty": "", "status": "Enrolled"},
    {"id": "SE239401", "name": "Leslie Martin", "attendance": 98, "a1_score": 73, "a1_status": "Completed", "a1_penalty": "🚩 Lateness Penalty (-5%)", "status": "Enrolled"},
    {"id": "SE645063", "name": "Jacob Watts", "attendance": 74, "a1_score": 79, "a1_status": "Completed", "a1_penalty": "🚩 Lateness Penalty (-5%)", "status": "Enrolled"},
    {"id": "SE537913", "name": "Michelle Vazquez", "attendance": 70, "a1_score": 77, "a1_status": "Completed", "a1_penalty": "", "status": "Enrolled"},
    {"id": "SE531790", "name": "Elizabeth Cohen", "attendance": 78, "a1_score": 86, "a1_status": "Completed", "a1_penalty": "", "status": "Enrolled"},
    {"id": "SE140602", "name": "Peter Montes", "attendance": 74, "a1_score": 68, "a1_status": "Completed", "a1_penalty": "🚩 Word Count Penalty (-10%)", "status": "Enrolled"},
    {"id": "SE570569", "name": "David Washington", "attendance": 86, "a1_score": 74, "a1_status": "Completed", "a1_penalty": "", "status": "Enrolled"},
    {"id": "SE623004", "name": "Mark Mitchell", "attendance": 100, "a1_score": 93, "a1_status": "Completed", "a1_penalty": "🚩 Word Count Penalty (-10%)", "status": "Enrolled"},
    {"id": "SE876035", "name": "Susan Franklin", "attendance": 62, "a1_score": 82, "a1_status": "Completed", "a1_penalty": "", "status": "Enrolled"},
    {"id": "SE783516", "name": "Anthony Torres", "attendance": 65, "a1_score": 80, "a1_status": "Completed", "a1_penalty": "", "status": "Enrolled"},
    {"id": "SE790326", "name": "Grant Cruz", "attendance": 78, "a1_score": 60, "a1_status": "Completed", "a1_penalty": "", "status": "Enrolled"},
    {"id": "SE841313", "name": "Penny Baker", "attendance": 65, "a1_score": 69, "a1_status": "Completed", "a1_penalty": "🚩 Word Count Penalty (-10%)", "status": "Enrolled"},
    {"id": "SE468237", "name": "Janice Ali", "attendance": 87, "a1_score": 65, "a1_status": "Completed", "a1_penalty": "🚩 Word Count Penalty (-10%)", "status": "Enrolled"},
    {"id": "SE511977", "name": "Eric Jones", "attendance": 65, "a1_score": 81, "a1_status": "Completed", "a1_penalty": "", "status": "Enrolled"},
    {"id": "SE156886", "name": "Nathan Miller", "attendance": 61, "a1_score": 53, "a1_status": "Completed", "a1_penalty": "", "status": "Enrolled"},
    {"id": "SE386757", "name": "Crystal Lopez", "attendance": 79, "a1_score": 88, "a1_status": "Completed", "a1_penalty": "🚩 Lateness Penalty (-5%)", "status": "Enrolled"},
    {"id": "SE944250", "name": "James Jones", "attendance": 98, "a1_score": 75, "a1_status": "Completed", "a1_penalty": "", "status": "Enrolled"},
    {"id": "SE436330", "name": "Troy Montoya", "attendance": 90, "a1_score": 60, "a1_status": "Completed", "a1_penalty": "🚩 Lateness Penalty (-5%)", "status": "Enrolled"},
    {"id": "SE428306", "name": "Leslie Weber", "attendance": 88, "a1_score": 57, "a1_status": "Completed", "a1_penalty": "🚩 Lateness Penalty (-5%)", "status": "Enrolled"},
    {"id": "SE975534", "name": "Charles Russell", "attendance": 79, "a1_score": 94, "a1_status": "Completed", "a1_penalty": "🚩 Lateness Penalty (-5%)", "status": "Enrolled"},
    {"id": "SE445186", "name": "Lisa Hart", "attendance": 63, "a1_score": 78, "a1_status": "Completed", "a1_penalty": "", "status": "Enrolled"},
    {"id": "SE578400", "name": "Robert Stark", "attendance": 70, "a1_score": 62, "a1_status": "Completed", "a1_penalty": "", "status": "Enrolled"},
    {"id": "SE707432", "name": "Megan Gomez", "attendance": 92, "a1_score": 84, "a1_status": "Completed", "a1_penalty": "", "status": "Enrolled"},
    {"id": "SE953868", "name": "Louis Brown DVM", "attendance": 63, "a1_score": 55, "a1_status": "Completed", "a1_penalty": "🚩 Word Count Penalty (-10%)", "status": "Enrolled"},
    {"id": "SE840287", "name": "Dwayne Allen", "attendance": 79, "a1_score": 85, "a1_status": "Completed", "a1_penalty": "", "status": "Enrolled"},
    {"id": "SE335879", "name": "Cynthia Howe", "attendance": 91, "a1_score": 95, "a1_status": "Completed", "a1_penalty": "🚩 Word Count Penalty (-10%)", "status": "Enrolled"},
    {"id": "SE841148", "name": "Joseph Taylor", "attendance": 82, "a1_score": 72, "a1_status": "Completed", "a1_penalty": "", "status": "Enrolled"},
    {"id": "SE522764", "name": "Mark Oliver", "attendance": 85, "a1_score": 59, "a1_status": "Completed", "a1_penalty": "🚩 Lateness Penalty (-5%)", "status": "Enrolled"},
    {"id": "SE156009", "name": "Alyssa Lopez", "attendance": 73, "a1_score": 54, "a1_status": "Completed", "a1_penalty": "", "status": "Enrolled"},
    {"id": "SE664708", "name": "Michael Brown", "attendance": 87, "a1_score": 55, "a1_status": "Completed", "a1_penalty": "🚩 Word Count Penalty (-10%)", "status": "Enrolled"},
    {"id": "SE858095", "name": "Ronald Chambers", "attendance": 84, "a1_score": 67, "a1_status": "Completed", "a1_penalty": "🚩 Lateness Penalty (-5%)", "status": "Enrolled"},
    {"id": "SE250418", "name": "James Lee", "attendance": 66, "a1_score": 71, "a1_status": "Completed", "a1_penalty": "", "status": "Enrolled"},
    {"id": "SE719192", "name": "Chris Johnson", "attendance": 67, "a1_score": 75, "a1_status": "Completed", "a1_penalty": "", "status": "Enrolled"},
    {"id": "SE500129", "name": "Caitlin Morales", "attendance": 86, "a1_score": 70, "a1_status": "Completed", "a1_penalty": "", "status": "Enrolled"},
    {"id": "SE353201", "name": "Scott Hernandez", "attendance": 86, "a1_score": 56, "a1_status": "Completed", "a1_penalty": "🚩 Lateness Penalty (-5%)", "status": "Enrolled"},
    {"id": "SE591446", "name": "Logan Clarke", "attendance": 61, "a1_score": 85, "a1_status": "Completed", "a1_penalty": "🚩 Word Count Penalty (-10%)", "status": "Enrolled"},
    {"id": "SE842140", "name": "Shawn Wolfe", "attendance": 92, "a1_score": 79, "a1_status": "Completed", "a1_penalty": "", "status": "Enrolled"},
    {"id": "SE953790", "name": "Morgan Osborne", "attendance": 60, "a1_score": 65, "a1_status": "Completed", "a1_penalty": "🚩 Word Count Penalty (-10%)", "status": "Enrolled"},
    {"id": "SE356986", "name": "Misty Ortega", "attendance": 96, "a1_score": 82, "a1_status": "Completed", "a1_penalty": "🚩 Word Count Penalty (-10%)", "status": "Enrolled"}
]



























# ✅ Lecturers (Can Add More Info Later)
lecturers = {
    "data_science": [
        {"id": "DS0001", "name": "Dr. Emily Carter"},
        {"id": "DS0002", "name": "Prof. Michael Reed"},
        {"id": "DS0003", "name": "Dr. Sarah Johnson"}
    ],
   
}
