# course_data.py

# ✅ Data Science Students
data_science_students = [
    {"id": "DS6846", "name": "Alex Carter", "attendance": 76, "exam_status": "Fit to Sit", "exam_score": 81,
     "a1_score": 59, "a1_status": "Completed", "a1_penalty": "", "a2_score": 81, "a2_status": "Completed",
     "a2_penalty": "🚩 Academic Misconduct", "status": "Enrolled"},
    {"id": "DS6478", "name": "Bella Sanders", "attendance": 98, "exam_status": "Fit to Sit", "exam_score": 53,
     "a1_score": 78, "a1_status": "Completed", "a1_penalty": "", "a2_score": 50, "a2_status": "Completed",
     "a2_penalty": "", "status": "Enrolled"},
    {"id": "DS1813", "name": "Cameron Hughes", "attendance": 60, "exam_status": "Fit to Sit", "exam_score": 52,
     "a1_score": 85, "a1_status": "Completed", "a1_penalty": "", "a2_score": 78, "a2_status": "Completed",
     "a2_penalty": "", "status": "Enrolled"},
    {"id": "DS9754", "name": "Diana Wright", "attendance": 39, "exam_status": "Fit to Sit", "exam_score": 84,
     "a1_score": 53, "a1_status": "Completed", "a1_penalty": "", "a2_score": 95, "a2_status": "Completed",
     "a2_penalty": "", "status": "Enrolled"},
    {"id": "DS4378", "name": "Ethan Parker", "attendance": 95, "exam_status": "Fit to Sit", "exam_score": 76,
     "a1_score": 73, "a1_status": "Completed", "a1_penalty": "", "a2_score": 87, "a2_status": "Completed",
     "a2_penalty": "", "status": "Enrolled"},
    {"id": "DS9791", "name": "Felicity James", "attendance": 93, "exam_status": "Fit to Sit", "exam_score": 53,
     "a1_score": 94, "a1_status": "Completed", "a1_penalty": "", "a2_score": 76, "a2_status": "Completed",
     "a2_penalty": "", "status": "Enrolled"},
    {"id": "DS2011", "name": "Gabriel Lewis", "attendance": 94, "exam_status": "Fit to Sit", "exam_score": 80,
     "a1_score": 94, "a1_status": "Completed", "a1_penalty": "🚩 Lateness Penalty (-5%)", "a2_score": 77,
     "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "DS6655", "name": "Hannah Stone", "attendance": 82, "exam_status": "Fit to Sit", "exam_score": 54,
     "a1_score": 71, "a1_status": "Completed", "a1_penalty": "", "a2_score": 70, "a2_status": "Completed",
     "a2_penalty": "", "status": "Enrolled"},
    {"id": "DS6446", "name": "Ian Turner", "attendance": 100, "exam_status": "Fit to Sit", "exam_score": 68,
     "a1_score": 95, "a1_status": "Completed", "a1_penalty": "", "a2_score": 78, "a2_status": "Completed",
     "a2_penalty": "", "status": "Enrolled"},
    {"id": "DS8178", "name": "Jasmine Collins", "attendance": 32, "exam_status": "Fit to Sit", "exam_score": 73,
     "a1_score": 78, "a1_status": "Completed", "a1_penalty": "", "a2_score": 75, "a2_status": "Completed",
     "a2_penalty": "🚩 Lateness Penalty (-5%)", "status": "Enrolled"},
    {"id": "DS2556", "name": "Kevin Morris", "attendance": 41, "exam_status": "Fit to Sit", "exam_score": 81,
     "a1_score": 72, "a1_status": "Completed", "a1_penalty": "", "a2_score": 91, "a2_status": "Completed",
     "a2_penalty": "🚩 Academic Misconduct", "status": "Enrolled"},
    {"id": "DS1387", "name": "Lara Watson", "attendance": 91, "exam_status": "Fit to Sit", "exam_score": 74,
     "a1_score": 65, "a1_status": "Completed", "a1_penalty": "", "a2_score": 84, "a2_status": "Completed",
     "a2_penalty": "", "status": "Enrolled"},
    {"id": "DS5339", "name": "Michael Griffin", "attendance": 81, "exam_status": "Fit to Sit", "exam_score": 81,
     "a1_score": 92, "a1_status": "Completed", "a1_penalty": "", "a2_score": 70, "a2_status": "Completed",
     "a2_penalty": "", "status": "Enrolled"},
    {"id": "DS1766", "name": "Natalie Cooper", "attendance": 93, "exam_status": "Fit to Sit", "exam_score": 82,
     "a1_score": 56, "a1_status": "Completed", "a1_penalty": "🚩 Exceptional Circumstances", "a2_score": 68,
     "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "DS1135", "name": "Owen Richardson", "attendance": 89, "exam_status": "Fit to Sit", "exam_score": 56,
     "a1_score": 90, "a1_status": "Completed", "a1_penalty": "", "a2_score": 81, "a2_status": "Completed",
     "a2_penalty": "", "status": "Enrolled"},
        {"id": "DS5293", "name": "Paige Scott", "attendance": 91, "exam_status": "Fit to Sit", "exam_score": 95,
     "a1_score": 66, "a1_status": "Completed", "a1_penalty": "", "a2_score": 55, "a2_status": "Completed",
     "a2_penalty": "", "status": "Enrolled"},
    {"id": "DS4568", "name": "Quentin Ramirez", "attendance": 99, "exam_status": "Fit to Sit", "exam_score": 52,
     "a1_score": 82, "a1_status": "Completed", "a1_penalty": "🚩 Lateness Penalty (-5%)", "a2_score": 0,
     "a2_status": "Not Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "DS3602", "name": "Rebecca Bennett", "attendance": 71, "exam_status": "Fit to Sit", "exam_score": 78,
     "a1_score": 78, "a1_status": "Completed", "a1_penalty": "", "a2_score": 79, "a2_status": "Completed",
     "a2_penalty": "", "status": "Enrolled"},
    {"id": "DS4981", "name": "Stephen Howard", "attendance": 71, "exam_status": "Fit to Sit", "exam_score": 80,
     "a1_score": 93, "a1_status": "Completed", "a1_penalty": "", "a2_score": 63, "a2_status": "Completed",
     "a2_penalty": "", "status": "Enrolled"},
    {"id": "DS2366", "name": "Tracy Bell", "attendance": 91, "exam_status": "Fit to Sit", "exam_score": 63,
     "a1_score": 63, "a1_status": "Completed", "a1_penalty": "", "a2_score": 76, "a2_status": "Completed",
     "a2_penalty": "", "status": "Enrolled"},
    {"id": "DS8924", "name": "Ulysses Barnes", "attendance": 71, "exam_status": "Fit to Sit", "exam_score": 54,
     "a1_score": 91, "a1_status": "Completed", "a1_penalty": "", "a2_score": 59, "a2_status": "Completed",
     "a2_penalty": "", "status": "Deferred"},
    {"id": "DS2684", "name": "Victoria Foster", "attendance": 78, "exam_status": "Fit to Sit", "exam_score": 70,
     "a1_score": 71, "a1_status": "Completed", "a1_penalty": "", "a2_score": 50, "a2_status": "Completed",
     "a2_penalty": "", "status": "Enrolled"},
    {"id": "DS2674", "name": "Walter Henderson", "attendance": 84, "exam_status": "Fit to Sit", "exam_score": 65,
     "a1_score": 53, "a1_status": "Completed", "a1_penalty": "", "a2_score": 68, "a2_status": "Completed",
     "a2_penalty": "", "status": "Enrolled"},
    {"id": "DS1149", "name": "Xander Nelson", "attendance": 56, "exam_status": "Fit to Sit", "exam_score": 56,
     "a1_score": 82, "a1_status": "Completed", "a1_penalty": "🚩 Exceptional Circumstances", "a2_score": 52,
     "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "DS5583", "name": "Yvette Campbell", "attendance": 63, "exam_status": "Fit to Sit", "exam_score": 75,
     "a1_score": 75, "a1_status": "Completed", "a1_penalty": "", "a2_score": 62, "a2_status": "Completed",
     "a2_penalty": "", "status": "Enrolled"},
    {"id": "DS1563", "name": "Zane Mitchell", "attendance": 93, "exam_status": "Fit to Sit", "exam_score": 57,
     "a1_score": 80, "a1_status": "Completed", "a1_penalty": "", "a2_score": 85, "a2_status": "Completed",
     "a2_penalty": "", "status": "Enrolled"},
    {"id": "DS6404", "name": "Amelia Ross", "attendance": 70, "exam_status": "Fit to Sit", "exam_score": 54,
     "a1_score": 68, "a1_status": "Completed", "a1_penalty": "🚩 Lateness Penalty (-5%)", "a2_score": 58,
     "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "DS8664", "name": "Benjamin Ward", "attendance": 55, "exam_status": "Fit to Sit", "exam_score": 50,
     "a1_score": 78, "a1_status": "Completed", "a1_penalty": "", "a2_score": 60, "a2_status": "Completed",
     "a2_penalty": "🚩 Academic Misconduct", "status": "Enrolled"},
    {"id": "DS9607", "name": "Chloe Edwards", "attendance": 88, "exam_status": "Fit to Sit", "exam_score": 62,
     "a1_score": 77, "a1_status": "Completed", "a1_penalty": "", "a2_score": 91, "a2_status": "Completed",
     "a2_penalty": "", "status": "Enrolled"},
    {"id": "DS5013", "name": "David Fisher", "attendance": 66, "exam_status": "Fit to Sit", "exam_score": 88,
     "a1_score": 90, "a1_status": "Completed", "a1_penalty": "", "a2_score": 53, "a2_status": "Completed",
     "a2_penalty": "", "status": "Enrolled"},
        {"id": "DS2760", "name": "Emma Butler", "attendance": 60, "exam_status": "Fit to Sit", "exam_score": 82,
     "a1_score": 72, "a1_status": "Completed", "a1_penalty": "", "a2_score": 72, "a2_status": "Completed",
     "a2_penalty": "", "status": "Enrolled"},
    {"id": "DS5971", "name": "Frederick Murphy", "attendance": 69, "exam_status": "Fit to Sit", "exam_score": 92,
     "a1_score": 75, "a1_status": "Completed", "a1_penalty": "", "a2_score": 50, "a2_status": "Completed",
     "a2_penalty": "", "status": "Deferred"},
    {"id": "DS2594", "name": "Grace Price", "attendance": 79, "exam_status": "Fit to Sit", "exam_score": 62,
     "a1_score": 51, "a1_status": "Completed", "a1_penalty": "🚩 Exceptional Circumstances", "a2_score": 91,
     "a2_status": "Completed", "a2_penalty": "", "status": "Dropped"},
    {"id": "DS1207", "name": "Henry Stewart", "attendance": 55, "exam_status": "Fit to Sit", "exam_score": 65,
     "a1_score": 60, "a1_status": "Completed", "a1_penalty": "", "a2_score": 50, "a2_status": "Completed",
     "a2_penalty": "", "status": "Enrolled"},
    {"id": "DS8709", "name": "Isabella Torres", "attendance": 88, "exam_status": "Fit to Sit", "exam_score": 52,
     "a1_score": 54, "a1_status": "Completed", "a1_penalty": "", "a2_score": 90, "a2_status": "Completed",
     "a2_penalty": "", "status": "Enrolled"},
    {"id": "DS9507", "name": "Jackie Peterson", "attendance": 68, "exam_status": "Fit to Sit", "exam_score": 88,
     "a1_score": 92, "a1_status": "Completed", "a1_penalty": "", "a2_score": 92, "a2_status": "Completed",
     "a2_penalty": "", "status": "Enrolled"},
    {"id": "DS1882", "name": "Kurt Bailey", "attendance": 98, "exam_status": "Fit to Sit", "exam_score": 61,
     "a1_score": 88, "a1_status": "Completed", "a1_penalty": "", "a2_score": 54, "a2_status": "Completed",
     "a2_penalty": "", "status": "Enrolled"},
    {"id": "DS9592", "name": "Lucy Jenkins", "attendance": 45, "exam_status": "Fit to Sit", "exam_score": 91,
     "a1_score": 82, "a1_status": "Completed", "a1_penalty": "🚩 Academic Misconduct", "a2_score": 85,
     "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "DS9880", "name": "Mason Cooper", "attendance": 84, "exam_status": "Fit to Sit", "exam_score": 83,
     "a1_score": 0, "a1_status": "Not Completed", "a1_penalty": "", "a2_score": 57,
     "a2_status": "Completed", "a2_penalty": "🚩 Lateness Penalty (-5%)", "status": "Enrolled"},
    {"id": "DS6445", "name": "Nina Adams", "attendance": 91, "exam_status": "Fit to Sit", "exam_score": 73,
     "a1_score": 73, "a1_status": "Completed", "a1_penalty": "", "a2_score": 77, "a2_status": "Completed",
     "a2_penalty": "", "status": "Enrolled"},
    {"id": "DS8511", "name": "Oscar Flores", "attendance": 97, "exam_status": "Absent", "exam_score": 0,
     "a1_score": 56, "a1_status": "Completed", "a1_penalty": "", "a2_score": 91, "a2_status": "Completed",
     "a2_penalty": "", "status": "Deferred"},
    {"id": "DS6948", "name": "Penelope Russell", "attendance": 66, "exam_status": "Fit to Sit", "exam_score": 73,
     "a1_score": 70, "a1_status": "Completed", "a1_penalty": "🚩 Lateness Penalty (-5%)", "a2_score": 95,
     "a2_status": "Completed", "a2_penalty": "🚩 Academic Misconduct", "status": "Enrolled"},
    {"id": "DS5478", "name": "Ryan Powell", "attendance": 93, "exam_status": "Fit to Sit", "exam_score": 90,
     "a1_score": 58, "a1_status": "Completed", "a1_penalty": "🚩 Exceptional Circumstances", "a2_score": 95,
     "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "DS1215", "name": "Sophia Simmons", "attendance": 86, "exam_status": "Fit to Sit", "exam_score": 93,
     "a1_score": 67, "a1_status": "Completed", "a1_penalty": "", "a2_score": 83, "a2_status": "Completed",
     "a2_penalty": "", "status": "Enrolled"},
    {"id": "DS4834", "name": "Theodore White", "attendance": 58, "exam_status": "Fit to Sit", "exam_score": 68,
     "a1_score": 90, "a1_status": "Completed", "a1_penalty": "", "a2_score": 82, "a2_status": "Completed",
     "a2_penalty": "", "status": "Enrolled"},
    {"id": "DS7831", "name": "Ursula Martin", "attendance": 93, "exam_status": "Fit to Sit", "exam_score": 56,
     "a1_score": 0, "a1_status": "Not Completed", "a1_penalty": "🚩 Exceptional Circumstances", "a2_score": 76,
     "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "DS1767", "name": "Vince Brown", "attendance": 98, "exam_status": "Fit to Sit", "exam_score": 78,
     "a1_score": 74, "a1_status": "Completed", "a1_penalty": "", "a2_score": 64, "a2_status": "Completed",
     "a2_penalty": "", "status": "Dropped"},
    {"id": "DS8872", "name": "William Gonzales", "attendance": 76, "exam_status": "Fit to Sit", "exam_score": 62,
     "a1_score": 66, "a1_status": "Completed", "a1_penalty": "", "a2_score": 54, "a2_status": "Completed",
     "a2_penalty": "", "status": "Enrolled"},
    {"id": "DS1907", "name": "Xenia Moore", "attendance": 55, "exam_status": "Fit to Sit", "exam_score": 92,
     "a1_score": 85, "a1_status": "Completed", "a1_penalty": "", "a2_score": 68, "a2_status": "Completed",
     "a2_penalty": "", "status": "Enrolled"},
    {"id": "DS7683", "name": "Zoe Walker", "attendance": 63, "exam_status": "Fit to Sit", "exam_score": 87,
     "a1_score": 61, "a1_status": "Completed", "a1_penalty": "", "a2_score": 0, "a2_status": "Not Completed",
     "a2_penalty": "🚩 Academic Misconduct", "status": "Enrolled"}
]


software_engineering_students = [
    {"id": "SE8946", "name": "Alice Johnson", "attendance": 82, "exam_status": "Fit to Sit", "exam_score": 58, "a1_score": 73, "a1_status": "Completed", "a1_penalty": "", "a2_score": 65, "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "SE5918", "name": "Bob Smith", "attendance": 82, "exam_status": "Fit to Sit", "exam_score": 74, "a1_score": 81, "a1_status": "Completed", "a1_penalty": "", "a2_score": 74, "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "SE7494", "name": "Charlie Davis", "attendance": 95, "exam_status": "Fit to Sit", "exam_score": 75, "a1_score": 0, "a1_status": "Not Completed", "a1_penalty": "🚩 Academic Misconduct", "a2_score": 81, "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "SE1509", "name": "David Martinez", "attendance": 81, "exam_status": "Fit to Sit", "exam_score": 94, "a1_score": 73, "a1_status": "Completed", "a1_penalty": "", "a2_score": 67, "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "SE8253", "name": "Eve Brown", "attendance": 83, "exam_status": "Fit to Sit", "exam_score": 70, "a1_score": 69, "a1_status": "Completed", "a1_penalty": "", "a2_score": 95, "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "SE1744", "name": "Frank Wilson", "attendance": 73, "exam_status": "Fit to Sit", "exam_score": 62, "a1_score": 95, "a1_status": "Completed", "a1_penalty": "🚩 Exceptional Circumstances", "a2_score": 0, "a2_status": "Not Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "SE5043", "name": "Grace Taylor", "attendance": 55, "exam_status": "Fit to Sit", "exam_score": 91, "a1_score": 80, "a1_status": "Completed", "a1_penalty": "", "a2_score": 66, "a2_status": "Completed", "a2_penalty": "🚩 Academic Misconduct", "status": "Enrolled"},
    {"id": "SE8979", "name": "Hank Anderson", "attendance": 80, "exam_status": "Fit to Sit", "exam_score": 62, "a1_score": 87, "a1_status": "Completed", "a1_penalty": "", "a2_score": 71, "a2_status": "Completed", "a2_penalty": "🚩 Exceptional Circumstances", "status": "Enrolled"},
    {"id": "SE1968", "name": "Ivy Thomas", "attendance": 97, "exam_status": "Absent", "exam_score": 0, "a1_score": 79, "a1_status": "Completed", "a1_penalty": "", "a2_score": 79, "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "SE1852", "name": "Jack White", "attendance": 88, "exam_status": "Fit to Sit", "exam_score": 58, "a1_score": 71, "a1_status": "Completed", "a1_penalty": "", "a2_score": 77, "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "SE8330", "name": "Karen Harris", "attendance": 76, "exam_status": "Fit to Sit", "exam_score": 76, "a1_score": 93, "a1_status": "Completed", "a1_penalty": "", "a2_score": 0, "a2_status": "Absent", "a2_penalty": "", "status": "Enrolled"},
    {"id": "SE8811", "name": "Leo Martin", "attendance": 89, "exam_status": "Fit to Sit", "exam_score": 79, "a1_score": 0, "a1_status": "Not Completed", "a1_penalty": "", "a2_score": 94, "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "SE9771", "name": "Mona Clark", "attendance": 70, "exam_status": "Fit to Sit", "exam_score": 55, "a1_score": 76, "a1_status": "Completed", "a1_penalty": "", "a2_score": 92, "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "SE5353", "name": "Nathan Lewis", "attendance": 56, "exam_status": "Fit to Sit", "exam_score": 74, "a1_score": 91, "a1_status": "Completed", "a1_penalty": "🚩 Exceptional Circumstances", "a2_score": 0, "a2_status": "Absent", "a2_penalty": "", "status": "Enrolled"},
    {"id": "SE1179", "name": "Olivia Hall", "attendance": 85, "exam_status": "Fit to Sit", "exam_score": 78, "a1_score": 93, "a1_status": "Completed", "a1_penalty": "", "a2_score": 66, "a2_status": "Completed", "a2_penalty": "", "status": "Dropped"},
    {"id": "SE5838", "name": "Peter Allen", "attendance": 89, "exam_status": "Fit to Sit", "exam_score": 82, "a1_score": 85, "a1_status": "Completed", "a1_penalty": "", "a2_score": 81, "a2_status": "Completed", "a2_penalty": "", "status": "Deferred"},
    {"id": "SE4247", "name": "Quincy Young", "attendance": 62, "exam_status": "Fit to Sit", "exam_score": 89, "a1_score": 0, "a1_status": "Not Completed", "a1_penalty": "", "a2_score": 76, "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "SE4796", "name": "Rachel King", "attendance": 78, "exam_status": "Fit to Sit", "exam_score": 56, "a1_score": 78, "a1_status": "Completed", "a1_penalty": "", "a2_score": 65, "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "SE3642", "name": "Steve Wright", "attendance": 89, "exam_status": "Fit to Sit", "exam_score": 81, "a1_score": 80, "a1_status": "Completed", "a1_penalty": "🚩 Academic Misconduct", "a2_score": 91, "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "SE3570", "name": "Tina Scott", "attendance": 94, "exam_status": "Fit to Sit", "exam_score": 67, "a1_score": 86, "a1_status": "Completed", "a1_penalty": "🚩 Exceptional Circumstances", "a2_score": 0, "a2_status": "Not Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "SE3688", "name": "Uma Green", "attendance": 99, "exam_status": "Fit to Sit", "exam_score": 74, "a1_score": 92, "a1_status": "Completed", "a1_penalty": "", "a2_score": 76, "a2_status": "Completed", "a2_penalty": "", "status": "Deferred"},
    {"id": "SE9940", "name": "Victor Adams", "attendance": 76, "exam_status": "Fit to Sit", "exam_score": 82, "a1_score": 70, "a1_status": "Completed", "a1_penalty": "", "a2_score": 86, "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "SE5462", "name": "Wendy Baker", "attendance": 76, "exam_status": "Fit to Sit", "exam_score": 72, "a1_score": 79, "a1_status": "Completed", "a1_penalty": "", "a2_score": 66, "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "SE4267", "name": "Xander Nelson", "attendance": 75, "exam_status": "Fit to Sit", "exam_score": 63, "a1_score": 91, "a1_status": "Completed", "a1_penalty": "", "a2_score": 92, "a2_status": "Completed", "a2_penalty": "", "status": "Deferred"},
    {"id": "SE2196", "name": "Yvonne Carter", "attendance": 70, "exam_status": "Fit to Sit", "exam_score": 70, "a1_score": 66, "a1_status": "Completed", "a1_penalty": "", "a2_score": 84, "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "SE3056", "name": "Zachary Mitchell", "attendance": 96, "exam_status": "Fit to Sit", "exam_score": 94, "a1_score": 0, "a1_status": "Absent", "a1_penalty": "", "a2_score": 90, "a2_status": "Completed", "a2_penalty": "🚩 Word Count Penalty (-10%)", "status": "Enrolled"},
    {"id": "SE3902", "name": "Aaron Perez", "attendance": 60, "exam_status": "Fit to Sit", "exam_score": 65, "a1_score": 90, "a1_status": "Completed", "a1_penalty": "", "a2_score": 84, "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "SE5236", "name": "Bella Roberts", "attendance": 70, "exam_status": "Fit to Sit", "exam_score": 58, "a1_score": 91, "a1_status": "Completed", "a1_penalty": "", "a2_score": 75, "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "SE9158", "name": "Cody Gonzalez", "attendance": 95, "exam_status": "Fit to Sit", "exam_score": 76, "a1_score": 81, "a1_status": "Completed", "a1_penalty": "", "a2_score": 92, "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "SE8950", "name": "Diana Campbell", "attendance": 93, "exam_status": "Fit to Sit", "exam_score": 61, "a1_score": 95, "a1_status": "Completed", "a1_penalty": "", "a2_score": 84, "a2_status": "Completed", "a2_penalty": "", "status": "Dropped"},
    {"id": "SE1967", "name": "Ethan Rodriguez", "attendance": 100, "exam_status": "Fit to Sit", "exam_score": 84, "a1_score": 96, "a1_status": "Completed", "a1_penalty": "🚩 Word Count Penalty (-10%)", "a2_score": 68, "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "SE8256", "name": "Fiona Moore", "attendance": 92, "exam_status": "Fit to Sit", "exam_score": 74, "a1_score": 89, "a1_status": "Completed", "a1_penalty": "", "a2_score": 87, "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "SE4532", "name": "George Edwards", "attendance": 88, "exam_status": "Fit to Sit", "exam_score": 66, "a1_score": 84, "a1_status": "Completed", "a1_penalty": "", "a2_score": 76, "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "SE1517", "name": "Holly Flores", "attendance": 86, "exam_status": "Fit to Sit", "exam_score": 78, "a1_score": 97, "a1_status": "Completed", "a1_penalty": "", "a2_score": 67, "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "SE7469", "name": "Ian Cooper", "attendance": 97, "exam_status": "Fit to Sit", "exam_score": 75, "a1_score": 81, "a1_status": "Completed", "a1_penalty": "", "a2_score": 69, "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "SE8148", "name": "Julia Murphy", "attendance": 96, "exam_status": "Fit to Sit", "exam_score": 58, "a1_score": 91, "a1_status": "Completed", "a1_penalty": "", "a2_score": 86, "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "SE1419", "name": "Kevin Reed", "attendance": 72, "exam_status": "Fit to Sit", "exam_score": 88, "a1_score": 84, "a1_status": "Completed", "a1_penalty": "", "a2_score": 80, "a2_status": "Completed", "a2_penalty": "🚩 Exceptional Circumstances", "status": "Enrolled"},
    {"id": "SE6287", "name": "Laura Cox", "attendance": 98, "exam_status": "Fit to Sit", "exam_score": 79, "a1_score": 76, "a1_status": "Completed", "a1_penalty": "", "a2_score": 71, "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "SE3159", "name": "Mike Ward", "attendance": 58, "exam_status": "Fit to Sit", "exam_score": 56, "a1_score": 77, "a1_status": "Completed", "a1_penalty": "", "a2_score": 75, "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "SE3655", "name": "Nina Peterson", "attendance": 85, "exam_status": "Fit to Sit", "exam_score": 88, "a1_score": 85, "a1_status": "Completed", "a1_penalty": "", "a2_score": 73, "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "SE9723", "name": "Oscar Gray", "attendance": 70, "exam_status": "Fit to Sit", "exam_score": 79, "a1_score": 86, "a1_status": "Completed", "a1_penalty": "🚩 Word Count Penalty (-10%)", "a2_score": 69, "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "SE9035", "name": "Paula Jenkins", "attendance": 86, "exam_status": "Fit to Sit", "exam_score": 88, "a1_score": 72, "a1_status": "Completed", "a1_penalty": "", "a2_score": 84, "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "SE9083", "name": "Quinn Russell", "attendance": 61, "exam_status": "Fit to Sit", "exam_score": 79, "a1_score": 94, "a1_status": "Completed", "a1_penalty": "", "a2_score": 72, "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "SE2110", "name": "Randy Torres", "attendance": 90, "exam_status": "Fit to Sit", "exam_score": 77, "a1_score": 78, "a1_status": "Completed", "a1_penalty": "", "a2_score": 98, "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "SE6193", "name": "Samantha Stevens", "attendance": 89, "exam_status": "Fit to Sit", "exam_score": 92, "a1_score": 65, "a1_status": "Completed", "a1_penalty": "", "a2_score": 73, "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "SE4227", "name": "Tommy Parker", "attendance": 83, "exam_status": "Fit to Sit", "exam_score": 63, "a1_score": 84, "a1_status": "Completed", "a1_penalty": "", "a2_score": 0, "a2_status": "Not Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "SE1890", "name": "Ursula Evans", "attendance": 71, "exam_status": "Fit to Sit", "exam_score": 84, "a1_score": 92, "a1_status": "Completed", "a1_penalty": "", "a2_score": 71, "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "SE1314", "name": "Vince Morgan", "attendance": 80, "exam_status": "Fit to Sit", "exam_score": 74, "a1_score": 84, "a1_status": "Completed", "a1_penalty": "", "a2_score": 97, "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "SE5890", "name": "Whitney Bell", "attendance": 85, "exam_status": "Fit to Sit", "exam_score": 89, "a1_score": 0, "a1_status": "Absent", "a1_penalty": "", "a2_score": 84, "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"},
    {"id": "SE3935", "name": "Xavier Phillips", "attendance": 70, "exam_status": "Fit to Sit", "exam_score": 62, "a1_score": 98, "a1_status": "Completed", "a1_penalty": "", "a2_score": 83, "a2_status": "Completed", "a2_penalty": "", "status": "Enrolled"}
]
























# ✅ Lecturers (Can Add More Info Later)
lecturers = {
    "data_science": [
        {"id": "DS0001", "name": "Dr. Emily Carter"},
        {"id": "DS0002", "name": "Prof. Michael Reed"},
        {"id": "DS0003", "name": "Dr. Sarah Johnson"}
    ],
   
}
